"""
Script to convert measured 3x2pt Pseudo-Cl power spectra (generated by measure_cat_3x2pt_pcls.py) into bandpowers. We
also make a theoretical prediction for the expected bandpowers based on the fiducial cosmology generated by CosmoSIS
"""

import os
import sys
import shutil
import linecache
import configparser
import numpy as np
import healpy as hp
import pymaster as nmt
from collections import defaultdict
import likelihood.mask as mask


def measure_bps_config(pipeline_variables_path):

    """
    Create a dictionary of parameters that will be useful to calculate measure Pseudo bandpowers (e.g. number of bins,
    realisations, mask etc.)

    Parameters
    ----------
    pipeline_variables_path (str):  Path to location of pipeline variables file ('set_variables_3x2pt_measurement.ini')

    Returns
    -------
    Dictionary of parameters used by this script to measure 3x2pt Pseudo bandpowers
    """

    config = configparser.ConfigParser()
    config.read(pipeline_variables_path)

    save_dir = str(config['simulation_setup']['SIMULATION_SAVE_DIR'])
    nbins = int(config['redshift_distribution']['N_ZBIN'])
    nside = int(float(config['simulation_setup']['NSIDE']))
    no_iter = int(config['simulation_setup']['REALISATIONS'])
    mask_path = str(config['measurement_setup']['PATH_TO_MASK'])
    cmb_mask_path = str(config['measurement_setup']['PATH_TO_CMB_MASK'])

    input_lmin = int(float(config['simulation_setup']['INPUT_ELL_MIN']))
    input_lmax = int(float(config['simulation_setup']['INPUT_ELL_MAX']))

    output_lmin_shear = int(float(config['measurement_setup']['OUTPUT_ELL_MIN_EE']))
    output_lmax_shear_config = config['measurement_setup']['OUTPUT_ELL_MAX_EE']
    output_lmax_shear = [int(float(i)) for i in output_lmax_shear_config.split(',')]

    output_lmin_galaxy_shear = int(float(config['measurement_setup']['OUTPUT_ELL_MIN_NE']))
    output_lmax_galaxy_shear_config = config['measurement_setup']['OUTPUT_ELL_MAX_NE']
    output_lmax_galaxy_shear = [int(float(i)) for i in output_lmax_galaxy_shear_config.split(',')]

    output_lmin_galaxy = int(float(config['measurement_setup']['OUTPUT_ELL_MIN_NN']))
    output_lmax_galaxy_config = config['measurement_setup']['OUTPUT_ELL_MAX_NN']
    output_lmax_galaxy = [int(float(i)) for i in output_lmax_galaxy_config.split(',')]

    output_lmin_cmbkk = int(float(config['measurement_setup']['OUTPUT_ELL_MIN_CMBKK']))
    output_lmax_cmbkk = int(float(config['measurement_setup']['OUTPUT_ELL_MAX_CMBKK']))

    output_lmin_cmbkk_galaxy = int(float(config['measurement_setup']['OUTPUT_ELL_MIN_CMBKK_N']))
    output_lmax_cmbkk_galaxy_config = config['measurement_setup']['OUTPUT_ELL_MAX_CMBKK_N']
    output_lmax_cmbkk_galaxy = [int(float(i)) for i in output_lmax_cmbkk_galaxy_config.split(',')]

    output_lmin_cmbkk_shear = int(float(config['measurement_setup']['OUTPUT_ELL_MIN_CMBKK_E']))
    output_lmax_cmbkk_shear_config = config['measurement_setup']['OUTPUT_ELL_MAX_CMBKK_E']
    output_lmax_cmbkk_shear = [int(float(i)) for i in output_lmax_cmbkk_shear_config.split(',')]

    n_bandpowers = int(float(config['measurement_setup']['N_BANDPOWERS']))
    bandpower_spacing = str(config['measurement_setup']['BANDPOWER_SPACING'])
    accepted_bp_spacings = {'log', 'lin', 'custom'}

    if bandpower_spacing not in accepted_bp_spacings:
        print('Error! Bandpower Spacing Not Recognised - Exiting...')
        sys.exit()

    elif bandpower_spacing == 'log':
        bp_bin_edges_galaxy = [np.logspace(np.log10(output_lmin_galaxy + 1e-5), np.log10(output_lmax_galaxy_i + 1e-5), n_bandpowers + 1) for output_lmax_galaxy_i in output_lmax_galaxy]
        bp_bin_edges_galaxy_shear = [np.logspace(np.log10(output_lmin_galaxy_shear + 1e-5), np.log10(output_lmax_galaxy_shear_i + 1e-5), n_bandpowers + 1) for output_lmax_galaxy_shear_i in output_lmax_galaxy_shear]
        bp_bin_edges_shear = [np.logspace(np.log10(output_lmin_shear + 1e-5), np.log10(output_lmax_shear_i + 1e-5), n_bandpowers + 1) for output_lmax_shear_i in output_lmax_shear]
        bp_bin_edges_cmbkk = np.logspace(np.log10(output_lmin_cmbkk + 1e-5), np.log10(output_lmax_cmbkk + 1e-5), n_bandpowers + 1)
        bp_bin_edges_cmbkk_galaxy = [np.logspace(np.log10(output_lmin_cmbkk_galaxy + 1e-5), np.log10(output_lmax_cmbkk_galaxy_i + 1e-5), n_bandpowers + 1) for output_lmax_cmbkk_galaxy_i in output_lmax_cmbkk_galaxy]
        bp_bin_edges_cmbkk_shear = [np.logspace(np.log10(output_lmin_cmbkk_shear + 1e-5), np.log10(output_lmax_cmbkk_shear_i + 1e-5), n_bandpowers + 1) for output_lmax_cmbkk_shear_i in output_lmax_cmbkk_shear]

    elif bandpower_spacing == 'lin':
        # bp_bin_edges = np.linspace(output_lmin + 1e-5, output_lmax + 1e-5, n_bandpowers + 1)
        bp_bin_edges_galaxy = [np.linspace(output_lmin_galaxy + 1e-5, output_lmax_galaxy_i + 1e-5, n_bandpowers + 1) for output_lmax_galaxy_i in output_lmax_galaxy]
        bp_bin_edges_galaxy_shear = [np.linspace(output_lmin_galaxy_shear + 1e-5, output_lmax_galaxy_shear_i + 1e-5, n_bandpowers + 1) for output_lmax_galaxy_shear_i in output_lmax_galaxy_shear]
        bp_bin_edges_shear = [np.linspace(output_lmin_shear + 1e-5, output_lmax_shear_i + 1e-5, n_bandpowers + 1) for output_lmax_shear_i in output_lmax_shear]
        bp_bin_edges_cmbkk = np.linspace(output_lmin_cmbkk + 1e-5, output_lmax_cmbkk + 1e-5, n_bandpowers + 1)
        bp_bin_edges_cmbkk_galaxy = [np.linspace(output_lmin_cmbkk_galaxy + 1e-5, output_lmax_cmbkk_galaxy_i + 1e-5, n_bandpowers + 1) for output_lmax_cmbkk_galaxy_i in output_lmax_cmbkk_galaxy]
        bp_bin_edges_cmbkk_shear = [np.linspace(output_lmin_cmbkk_shear + 1e-5, output_lmax_cmbkk_shear_i + 1e-5, n_bandpowers + 1) for output_lmax_cmbkk_shear_i in output_lmax_cmbkk_shear]

    elif bandpower_spacing == 'custom':
        # Placeholder at the moment!!!
        bp_bin_edges = np.empty(n_bandpowers)
        bp_bin_edges_galaxy = np.empty(n_bandpowers)
        bp_bin_edges_galaxy_shear = np.empty(n_bandpowers)
        bp_bin_edges_shear = np.empty(n_bandpowers)
        bp_bin_edges_cmbkk = np.empty(n_bandpowers)
        bp_bin_edges_cmbkk_galaxy = np.empty(n_bandpowers)
        bp_bin_edges_cmbkk_shear = np.empty(n_bandpowers)

        print('Need to figure out how to do something. Future JWong todo.')
        # I think it should probably be something like set_variables.ini points to a file in which the bandpower edges
        # are stored. Probably need to think about format for this. Also where to calculate this? Or just let user do
        # edges = np.loadtxt(dir + str(config['measure_3x2pt_cls']['BANDPOWER_EDGES']))
        # Then might need to transpose depending on the structure of supplied bandpower edges.
        # if os.path.isfile(dir + str(config['measure_3x2pt_cls']['BANDPOWER_EDGES'])) is False:
        #     print('WARNING - Must supply custom bandpower edges')
        #     sys.exit()

    else:
        # Bandpower type not recognised
        sys.exit()

    bp_bins_galaxy = [nmt.NmtBin.from_edges(
        ell_ini=np.ceil(bp_bin_edges_galaxy_i).astype(int)[:-1],
        ell_end=np.ceil(bp_bin_edges_galaxy_i).astype(int)[1:]) for bp_bin_edges_galaxy_i in bp_bin_edges_galaxy]
    ell_arr_galaxy = [bp_bins_galaxy_i.get_effective_ells() for bp_bins_galaxy_i in bp_bins_galaxy]

    bp_bins_galaxy_shear = [nmt.NmtBin.from_edges(
        ell_ini=np.ceil(bp_bin_edges_galaxy_shear_i).astype(int)[:-1],
        ell_end=np.ceil(bp_bin_edges_galaxy_shear_i).astype(int)[1:]) for bp_bin_edges_galaxy_shear_i in bp_bin_edges_galaxy_shear]
    ell_arr_galaxy_shear = [bp_bins_galaxy_shear_i.get_effective_ells() for bp_bins_galaxy_shear_i in bp_bins_galaxy_shear]

    bp_bins_shear = [nmt.NmtBin.from_edges(
        ell_ini=np.ceil(bp_bin_edges_shear_i).astype(int)[:-1],
        ell_end=np.ceil(bp_bin_edges_shear_i).astype(int)[1:]) for bp_bin_edges_shear_i in bp_bin_edges_shear]
    ell_arr_shear = [bp_bins_shear_i.get_effective_ells() for bp_bins_shear_i in bp_bins_shear]

    bp_bins_cmbkk = nmt.NmtBin.from_edges(
        ell_ini=np.ceil(bp_bin_edges_cmbkk).astype(int)[:-1],
        ell_end=np.ceil(bp_bin_edges_cmbkk).astype(int)[1:])
    ell_arr_cmbkk = bp_bins_cmbkk.get_effective_ells()

    bp_bins_cmbkk_galaxy = [nmt.NmtBin.from_edges(
        ell_ini=np.ceil(bp_bin_edges_cmbkk_galaxy_i).astype(int)[:-1],
        ell_end=np.ceil(bp_bin_edges_cmbkk_galaxy_i).astype(int)[1:]) for bp_bin_edges_cmbkk_galaxy_i in bp_bin_edges_cmbkk_galaxy]
    ell_arr_cmbkk_galaxy = [bp_bins_cmbkk_galaxy_i.get_effective_ells() for bp_bins_cmbkk_galaxy_i in bp_bins_cmbkk_galaxy]

    bp_bins_cmbkk_shear = [nmt.NmtBin.from_edges(
        ell_ini=np.ceil(bp_bin_edges_cmbkk_shear_i).astype(int)[:-1],
        ell_end=np.ceil(bp_bin_edges_cmbkk_shear_i).astype(int)[1:]) for bp_bin_edges_cmbkk_shear_i in bp_bin_edges_cmbkk_shear]
    ell_arr_cmbkk_shear = [bp_bins_cmbkk_shear_i.get_effective_ells() for bp_bins_cmbkk_shear_i in bp_bins_cmbkk_shear]

    pbl_shear = [mask.get_binning_matrix(
        n_bandpowers=n_bandpowers,
        output_lmin=output_lmin_shear,
        output_lmax=output_lmax_shear_i,
        bp_spacing=bandpower_spacing) for output_lmax_shear_i in output_lmax_shear]

    pbl_galaxy_shear = [mask.get_binning_matrix(
        n_bandpowers=n_bandpowers,
        output_lmin=output_lmin_galaxy_shear,
        output_lmax=output_lmax_galaxy_shear_i,
        bp_spacing=bandpower_spacing) for output_lmax_galaxy_shear_i in output_lmax_galaxy_shear]

    pbl_galaxy = [mask.get_binning_matrix(
        n_bandpowers=n_bandpowers,
        output_lmin=output_lmin_galaxy,
        output_lmax=output_lmax_galaxy_i,
        bp_spacing=bandpower_spacing) for output_lmax_galaxy_i in output_lmax_galaxy]

    pbl_cmbkk = mask.get_binning_matrix(
        n_bandpowers=n_bandpowers,
        output_lmin=output_lmin_cmbkk,
        output_lmax=output_lmax_cmbkk,
        bp_spacing=bandpower_spacing)

    pbl_cmbkk_galaxy = [mask.get_binning_matrix(
        n_bandpowers=n_bandpowers,
        output_lmin=output_lmin_cmbkk_galaxy,
        output_lmax=output_lmax_cmbkk_galaxy_i,
        bp_spacing=bandpower_spacing) for output_lmax_cmbkk_galaxy_i in output_lmax_cmbkk_galaxy]

    pbl_cmbkk_shear = [mask.get_binning_matrix(
        n_bandpowers=n_bandpowers,
        output_lmin=output_lmin_cmbkk_shear,
        output_lmax=output_lmax_cmbkk_shear_i,
        bp_spacing=bandpower_spacing) for output_lmax_cmbkk_shear_i in output_lmax_cmbkk_shear]

    # Prepare config dictionary
    config_dict = {
        'save_dir': save_dir,
        'nbins': nbins,
        'nside': nside,
        'no_iter': no_iter,
        'mask_path': mask_path,
        'cmb_mask_path': cmb_mask_path,
        'input_lmin': input_lmin,
        'input_lmax': input_lmax,
        'n_bandpowers': n_bandpowers,
        'bandpower_spacing': bandpower_spacing,
        'output_lmin_shear': output_lmin_shear,
        'output_lmax_shear': output_lmax_shear,
        'pbl_shear': pbl_shear,
        'bp_bins_shear': bp_bins_shear,
        'ell_arr_shear': ell_arr_shear,
        'output_lmin_galaxy_shear': output_lmin_galaxy_shear,
        'output_lmax_galaxy_shear': output_lmax_galaxy_shear,
        'pbl_galaxy_shear': pbl_galaxy_shear,
        'bp_bins_galaxy_shear': bp_bins_galaxy_shear,
        'ell_arr_galaxy_shear': ell_arr_galaxy_shear,
        'output_lmin_galaxy': output_lmin_galaxy,
        'output_lmax_galaxy': output_lmax_galaxy,
        'pbl_galaxy': pbl_galaxy,
        'bp_bins_galaxy': bp_bins_galaxy,
        'ell_arr_galaxy': ell_arr_galaxy,
        'output_lmin_cmbkk': output_lmin_cmbkk,
        'output_lmax_cmbkk': output_lmax_cmbkk,
        'pbl_cmbkk': pbl_cmbkk,
        'bp_bins_cmbkk': bp_bins_cmbkk,
        'ell_arr_cmbkk': ell_arr_cmbkk,
        'output_lmin_cmbkk_galaxy': output_lmin_cmbkk_galaxy,
        'output_lmax_cmbkk_galaxy': output_lmax_cmbkk_galaxy,
        'pbl_cmbkk_galaxy': pbl_cmbkk_galaxy,
        'bp_bins_cmbkk_galaxy': bp_bins_cmbkk_galaxy,
        'ell_arr_cmbkk_galaxy': ell_arr_cmbkk_galaxy,
        'output_lmin_cmbkk_shear': output_lmin_cmbkk_shear,
        'output_lmax_cmbkk_shear': output_lmax_cmbkk_shear,
        'pbl_cmbkk_shear': pbl_cmbkk_shear,
        'bp_bins_cmbkk_shear': bp_bins_cmbkk_shear,
        'ell_arr_cmbkk_shear': ell_arr_cmbkk_shear,
    }

    return config_dict


def measured_cls_to_obs_cls(measured_cls_dir, obs_cls_dir, bin_i, bin_j, lmin_out, lmax_out):

    """
    Convert 'raw' Pseudo-Cls to an 'observed' data vector - just specifies the ell range that is kept to then convert
    to bandpowers

    Parameters
    ----------
    measured_cls_dir (str): Path to 3xp2t power spectra as measured and averaged over by measure_cat_3x2pt_pcls.py and
                            av_cls.py
    obs_cls_dir (str):  Path to location to store scale-cut (in ell) 3x2pt power spectra
    bin_i (float):  Tomographic bin id number of the first field
    bin_j (float):  Tomographic bin id number of the second field
    lmin_out (float):   Minimum ell that the power spectra are saved to for conversion into bandpowers
    lmax_out (float):   Maximum ell that the power spectra are saved to for conversion into bandpowers

    Returns
    -------
    Saves txt file of the power spectra that have been cut to specified ell range.
    """

    measured_cl = np.loadtxt(measured_cls_dir + 'bin_{}_{}.txt'.format(bin_i, bin_j))
    obs_cl = measured_cl[lmin_out:lmax_out + 1]

    if not os.path.exists(obs_cls_dir):
        os.makedirs(obs_cls_dir)

    np.savetxt(obs_cls_dir + 'bin_{}_{}.txt'.format(bin_i, bin_j), obs_cl)

    measured_ell = np.loadtxt(measured_cls_dir + 'ell.txt')
    obs_ell = measured_ell[lmin_out:lmax_out + 1]

    np.savetxt(obs_cls_dir + 'ell_bin_{}_{}.txt'.format(bin_i,bin_j), np.transpose(obs_ell))


def cl_to_bp(cl_dir, bp_dir, bin_i, bin_j, pbl, ell_arr=None):

    """
    Function to convert measured power spectra to bandpowers

    Parameters
    ----------
    cl_dir (str):   Path to 3x2pt power spectra
    bp_dir (str):   Path to save measured 3x2pt bandpowers
    bin_i (float):  Tomographic bin id number of the first field
    bin_j (float):  Tomographic bin id number of the second field
    pbl (arr):      Pbl matrix to convert Cls to bandpowers. Pbl matrix will be generated in the main function and will
                    be specified to the chosen ell range.

    Returns
    -------
    Saves txt file of the measured 3x2pt bandpowers
    """

    this_cl = np.loadtxt(cl_dir + 'bin_{}_{}.txt'.format(bin_i, bin_j))
    this_bp = pbl @ this_cl

    if not os.path.exists(bp_dir):
        os.makedirs(bp_dir)

    np.savetxt(bp_dir + 'bin_{}_{}.txt'.format(bin_i, bin_j), this_bp)

    if ell_arr is not None:
        np.savetxt(bp_dir + 'ell_bp_bin_{}_{}.txt'.format(bin_i, bin_j), ell_arr)

def calc_stdem_bps(bp_dir, n_bps, bin_i, bin_j, realisations):

    """
    Function to calculate the standard error on mean across measured bandpowers for all realisations

    Parameters
    ----------
    bp_dir (str):   Path to txt files of the measured bandpowers for all realisations
    n_bps (float):  Number of bandpowers used
    bin_i (float):  Tomographic bin id number of the first field
    bin_j (float):  Tomographic bin id number of the second field
    realisations (float):   Number of realisations

    Returns
    -------
    Saves txt file of the standard error on mean for all tomographic 3x2pt bandpowers measured across all realisations.
    """

    bps_err = []

    for x in range(n_bps):

        bp_vals = []

        for y in range(realisations):
            bp_file = bp_dir + 'iter_{}/bin_{}_{}.txt'.format(y + 1, bin_i, bin_j)
            a = linecache.getline(
                bp_file,
                x + 1).split()
            bp_vals.append(float(a[0]))

        bp_vals = np.asarray(bp_vals)
        bp_av = np.zeros(len(bp_vals))
        bp_av += np.mean(bp_vals)

        bps_err.append(np.sqrt((sum((bp_vals - bp_av) ** 2)) / (realisations ** 2)))

    np.savetxt(bp_dir + 'bin_%s_%s_err.txt' % (bin_i, bin_j),
               np.transpose(bps_err))


###############################################################################################
# Following bit of code is to make a prediction for the theory bandpowers based on the survey
###############################################################################################

def setup_theory_cls(cl_dir, spectra_type, bin_i, bin_j):

    """
    Opens some theory Cls based on field type and bin combination to prepare for decoupling into a binned Pseudo-Cl
    Parameters
    ----------
    cl_dir (str):   Path to the fiducial 3x2pt full-sky power spectra
    spectra_type (str): Which spectra is being generated. For extracting the correct spectrum file.
    bin_i (float):  Tomographic bin id number of the first field
    bin_j (float):  Tomographic bin id number of the second field

    Returns
    -------
    Array of the fiducial power spectrum, and its path
    """

    accepted_spectra_types = {'TT', 'TE', 'TB', 'EE', 'EB', 'BE', 'BB', 'kk', 'gal_gal', 'gal_E', 'gal_B', 'kCMB_kCMB',
                              'kCMB_gal', 'kCMB_E', 'kCMB_B'}

    if spectra_type not in accepted_spectra_types:
        print(spectra_type)
        print('Error! Field Type Not Recognised - Exiting...')
        sys.exit()

    # Open correct cl folder - based on default CosmoSIS naming conventions

    cl_paths = {
        'TT': 'shear_cl/',
        'TE': 'null_spectra/',
        'TB': 'null_spectra/',
        'EE': 'shear_cl/',
        'EB': 'null_spectra/',
        'BE': 'null_spectra/',
        'BB': 'null_spectra/',
        'gal_gal': 'galaxy_cl/',
        'gal_E': 'galaxy_shear_cl/',
        'gal_B': 'null_spectra/',
        'kCMB_kCMB': 'cmbkappa_cl/',
        'kCMB_gal': 'galaxy_cmbkappa_cl/',
        'kCMB_E': 'shear_cmbkappa_cl/',
        'kCMB_B': 'null_spectra/'
    }

    theory_cls_dir = cl_dir + cl_paths[spectra_type]
    theory_cls = np.loadtxt(theory_cls_dir + 'bin_{}_{}.txt'.format(bin_i, bin_j))
    return theory_cls, theory_cls_dir


def pad_cls(lmin, input_cls):

    """
    Convenience function - in case lmin!=0, we need to pad the theory Cls with zeros at 0<=l<lmin in order to
    combine with the mixing + binning matrices used in NaMaster to generate a binned theoretical Pseudo-Cl
    Parameters
    ----------
    lmin (float):   Minimum ell of fiducial power spectra
    input_cls (arr):    Array of fiducial power spectrum values

    Returns
    -------

    """

    if lmin != 0:
        pad_cl_arr = np.zeros(lmin)
        input_cls = np.concatenate((pad_cl_arr, input_cls))
    else:
        pass
    return input_cls


def create_null_spectras(nbins, lmin, lmax, output_dir):

    """
    Create 'null spectra' of 'observed' data vector. Pipeline assumes only non-zero components are TT, EE, gal_gal,
    gal_shear (gal_E). So we need to create some 'zero' spectra of the same size as the non-zero components to do
    inference analysis, comparison testing, systematics analysis etc.

    Parameters
    ----------
    nbins (float):  Number of tomographic bins
    lmin (float):   Minimum ell of null power spectra. Should match the minimum ell used in measured_cls_to_obs_cls
    lmax (float):   Maximum ell of null power spectra. Should match the minimum ell used in measured_cls_to_obs_cls
    output_dir (str):   Path of location to save null power spectra

    Returns
    -------
    Saves txt file of null (zero) power spectra saved to an ell range that matches measured_cls_to_obs_cls
    """

    null_spectras_dir = output_dir + 'null_spectra/'
    if not os.path.exists(null_spectras_dir):
        os.makedirs(null_spectras_dir)

    null_ells = np.linspace(lmin, lmax + 1, (lmax - lmin) + 1)

    np.savetxt(null_spectras_dir + 'ell.txt',
               np.transpose(null_ells))

    for i in range(nbins):
        for j in range(nbins):
            null_cls = np.zeros(len(null_ells))
            np.savetxt(null_spectras_dir + 'bin_{}_{}.txt'.format(i + 1, j + 1),
                       np.transpose(null_cls))


def process_00_pcls(config_dict, theory_cl_dir, noise_cl_dir, spectra_type, bin_i, bin_j, obs_mask_path, output_lmin,
                    output_lmax, ell_arr, pbl):

    """
    Function to convert fiducial full-sky 00 components of the 3x2pt power spectra into predicted Pseudo-bandpowers.
    First couple the full-sky spectra with the mask to produce Pseudo-Cls. Then combine with the bandpower binning and
    include noise model.

    Parameters
    ----------
    config_dict (dict): Config dictionary of pipeline/conversion variables
    theory_cl_dir (str):    Path to location of fiducial full-sky power spectra
    noise_cl_dir (str):     Path to location of predicted noise power spectra
    spectra_type (str): Which spectra type (i.e. which component of the 3x2pt). For 00 must be 'TT' for shear, or
                        'gal_gal' for galaxy overdensity.
    bin_i (float):  Tomographic bin id number of the first field
    bin_j (float):  Tomographic bin id number of the second field
    obs_mask_path (str):    Path to mask describing observed footprint
    ell_arr (arr):  Array of the 'effective' ells that correspond to the bandpowers
    pbl (arr):  Bandpower conversion matrix

    Returns
    -------
    Saves fiducial model of the 3x2pt 00 Pseudo bandpowers that include contribution from the expected noise
    """

    input_lmin = config_dict['input_lmin']
    input_lmax = config_dict['input_lmax']

    nside = config_dict['nside']

    accepted_spectra_types = {'TT', 'gal_gal', 'kCMB_kCMB', 'kCMB_gal'}
    if spectra_type not in accepted_spectra_types:
        print('Warning! Field Type Not Recognised - Exiting...')
        sys.exit()

    if spectra_type == 'kCMB_gal':

        if obs_mask_path[0] == 'None':
            obs_mask = np.ones(hp.nside2npix(nside))
        else:
            obs_mask = hp.read_map(obs_mask_path[0])

        if obs_mask_path[1] == 'None':
            obs_mask_cmb = np.ones(hp.nside2npix(nside))
        else:
            obs_mask_cmb = hp.read_map(obs_mask_path[1])

        # lmax_sht here should be input lmax
        f0 = nmt.NmtField(mask=obs_mask, maps=None, spin=0, lmax_sht=input_lmax, lite=True)
        f0_cmb = nmt.NmtField(mask=obs_mask_cmb, maps=None, spin=0, lmax_sht=input_lmax, lite=True)

        w = nmt.NmtWorkspace()
        w.compute_coupling_matrix(f0, f0_cmb, bins=nmt.NmtBin.from_lmax_linear(input_lmax, 1))

    else:

        if obs_mask_path == 'None':
            obs_mask = np.ones(hp.nside2npix(nside))
        else:
            obs_mask = hp.read_map(obs_mask_path)

        # lmax_sht here should be input lmax
        f0 = nmt.NmtField(mask=obs_mask, maps=None, spin=0, lmax_sht=input_lmax, lite=True)

        w = nmt.NmtWorkspace()
        w.compute_coupling_matrix(f0, f0, bins=nmt.NmtBin.from_lmax_linear(input_lmax, 1))

    # theory cls go from input lmin to input lmax
    theory_cls, bp_save_dir = setup_theory_cls(
        cl_dir=theory_cl_dir,
        spectra_type=spectra_type,
        bin_i=bin_i,
        bin_j=bin_j)

    noise_cls = setup_theory_cls(
        cl_dir=noise_cl_dir,
        spectra_type=spectra_type,
        bin_i=bin_i,
        bin_j=bin_j)[0]

    theory_cls = pad_cls(lmin=input_lmin, input_cls=theory_cls)
    noise_cls = pad_cls(lmin=0, input_cls=noise_cls)
    # theory_cls = [theory_cls]
    theory_cls = [theory_cls+noise_cls]
    theory_pcl = w.couple_cell(theory_cls)
    binned_theory_pcl = pbl @ (theory_pcl[0][output_lmin:output_lmax + 1])

    np.savetxt(bp_save_dir + 'PCl_Bandpowers_{}_bin_{}_{}.txt'.format(spectra_type, bin_i, bin_j),
               np.transpose(binned_theory_pcl))

    if os.path.isfile(bp_save_dir + 'ell_bp_bin_{}_{}.txt'.format(bin_i,bin_j)) is False:
        np.savetxt(bp_save_dir + 'ell_bp_bin_{}_{}.txt'.format(bin_i,bin_j),
                   np.transpose(ell_arr))


def process_02_pcls(config_dict, theory_cl_dir, noise_cl_dir, spectra_type, bin_i, bin_j, obs_mask_path, output_lmin,
                    output_lmax, ell_arr, pbl):

    """
    Function to convert fiducial full-sky 02 components of the 3x2pt power spectra into predicted Pseudo-bandpowers.
    First couple the full-sky spectra with the mask to produce Pseudo-Cls. Then combine with the bandpower binning and
    include noise model.

    Parameters
    ----------
    config_dict (dict): Config dictionary of pipeline/conversion variables
    theory_cl_dir (str):    Path to location of fiducial full-sky power spectra
    noise_cl_dir (str):     Path to location of predicted noise power spectra
    spectra_type (str): Which spectra type (i.e. which component of the 3x2pt). For 02 must be 'TE' or 'TB' for shear,
                        or 'gal_E' or 'gal_B' for cross correlation between shear and galaxy overdensity.
    bin_i (float):  Tomographic bin id number of the first field
    bin_j (float):  Tomographic bin id number of the second field
    obs_mask_path (str):    Path to mask describing observed footprint
    ell_arr (arr):  Array of the 'effective' ells that correspond to the bandpowers
    pbl (arr):  Bandpower conversion matrix

    Returns
    -------
    Saves fiducial model of the 3x2pt 02 Pseudo bandpowers that include contribution from the expected noise.
    """

    input_lmin = config_dict['input_lmin']
    input_lmax = config_dict['input_lmax']

    nside = config_dict['nside']

    accepted_spectra_types = {'TE', 'TB', 'gal_E', 'gal_B', 'kCMB_E', 'kCMB_B'}
    if spectra_type not in accepted_spectra_types:
        print('Warning! Field Type Not Recognised - Exiting...')
        sys.exit()

    if spectra_type == 'kCMB_E' or spectra_type == 'kCMB_B':

        if obs_mask_path[0] == 'None':
            obs_mask = np.ones(hp.nside2npix(nside))
        else:
            obs_mask = hp.read_map(obs_mask_path[0])

        if obs_mask_path[1] == 'None':
            obs_mask_cmb = np.ones(hp.nside2npix(nside))
        else:
            obs_mask_cmb = hp.read_map(obs_mask_path[1])

        # obs_mask = hp.read_map(obs_mask_path[0])
        # obs_mask_cmb = hp.read_map(obs_mask_path[1])

        # lmax_sht here should be input lmax
        f0 = nmt.NmtField(mask=obs_mask_cmb, maps=None, spin=0, lmax_sht=input_lmax)
        f2 = nmt.NmtField(mask=obs_mask, maps=None, spin=2, lmax_sht=input_lmax)

        w = nmt.NmtWorkspace()
        w.compute_coupling_matrix(f0, f2, bins=nmt.NmtBin.from_lmax_linear(input_lmax, 1))

    else:

        if obs_mask_path == 'None':
            obs_mask = np.ones(hp.nside2npix(nside))
        else:
            obs_mask = hp.read_map(obs_mask_path)

        # obs_mask = hp.read_map(obs_mask_path)

        f0 = nmt.NmtField(mask=obs_mask, maps=None, spin=0, lmax_sht=input_lmax)
        f2 = nmt.NmtField(mask=obs_mask, maps=None, spin=2, lmax_sht=input_lmax)

        w = nmt.NmtWorkspace()
        w.compute_coupling_matrix(f0, f2, bins=nmt.NmtBin.from_lmax_linear(input_lmax, 1))

    binned_theory_pcls = defaultdict(list)

    if spectra_type == 'TE' or spectra_type == 'TB':
        theory_TE = pad_cls(
            lmin=input_lmin,
            input_cls=setup_theory_cls(
                cl_dir=theory_cl_dir,
                spectra_type='TE',
                bin_i=bin_i,
                bin_j=bin_j)[0])

        theory_TB = pad_cls(
            lmin=input_lmin,
            input_cls=setup_theory_cls(
                cl_dir=theory_cl_dir,
                spectra_type='TB',
                bin_i=bin_i,
                bin_j=bin_j)[0])

        noise_cls = pad_cls(
            lmin=0,
            input_cls=setup_theory_cls(
                cl_dir=noise_cl_dir,
                spectra_type=spectra_type,
                bin_i=bin_i,
                bin_j=bin_j)[0])

        # theory_cls = [theory_TE, theory_TB]
        theory_cls = [theory_TE+noise_cls, theory_TB+noise_cls]

        theory_pcl = w.couple_cell(theory_cls)

        # binned_theory_pcls['TE'] = pbl @ (theory_pcl[0][output_lmin:output_lmax + 1]
        #                                   + noise_cls[output_lmin:output_lmax + 1])
        # binned_theory_pcls['TB'] = pbl @ (theory_pcl[1][output_lmin:output_lmax + 1]
        #                                   + noise_cls[output_lmin:output_lmax + 1])

        binned_theory_pcls['TE'] = pbl @ (theory_pcl[0][output_lmin:output_lmax + 1])
        binned_theory_pcls['TB'] = pbl @ (theory_pcl[1][output_lmin:output_lmax + 1])

    elif spectra_type == 'gal_E' or spectra_type == 'gal_B':
        theory_gal_E = pad_cls(
            lmin=input_lmin,
            input_cls=setup_theory_cls(
                cl_dir=theory_cl_dir,
                spectra_type='gal_E',
                bin_i=bin_i,
                bin_j=bin_j)[0])

        theory_gal_B = pad_cls(
            lmin=input_lmin,
            input_cls=setup_theory_cls(
                cl_dir=theory_cl_dir,
                spectra_type='gal_B',
                bin_i=bin_i,
                bin_j=bin_j)[0])

        noise_cls = pad_cls(
            lmin=0,
            input_cls=setup_theory_cls(
                cl_dir=noise_cl_dir,
                spectra_type=spectra_type,
                bin_i=bin_i,
                bin_j=bin_j)[0])

        # theory_cls = [theory_gal_E, theory_gal_B]
        theory_cls = [theory_gal_E+noise_cls, theory_gal_B+noise_cls]

        theory_pcl = w.couple_cell(theory_cls)

        # binned_theory_pcls['gal_E'] = pbl @ (theory_pcl[0][output_lmin:output_lmax + 1]
        #                                      + noise_cls[output_lmin:output_lmax + 1])
        #
        # binned_theory_pcls['gal_B'] = pbl @ (theory_pcl[1][output_lmin:output_lmax + 1]
        #                                      + noise_cls[output_lmin:output_lmax + 1])

        binned_theory_pcls['gal_E'] = pbl @ (theory_pcl[0][output_lmin:output_lmax + 1])

        binned_theory_pcls['gal_B'] = pbl @ (theory_pcl[1][output_lmin:output_lmax + 1])

    elif spectra_type == 'kCMB_E' or spectra_type == 'kCMB_B':
        theory_kCMB_E = pad_cls(
            lmin=input_lmin,
            input_cls=setup_theory_cls(
                cl_dir=theory_cl_dir,
                spectra_type='kCMB_E',
                bin_i=bin_i,
                bin_j=bin_j)[0])

        theory_kCMB_B = pad_cls(
            lmin=input_lmin,
            input_cls=setup_theory_cls(
                cl_dir=theory_cl_dir,
                spectra_type='kCMB_B',
                bin_i=bin_i,
                bin_j=bin_j)[0])

        noise_cls = pad_cls(
            lmin=0,
            input_cls=setup_theory_cls(
                cl_dir=noise_cl_dir,
                spectra_type=spectra_type,
                bin_i=bin_i,
                bin_j=bin_j)[0])

        # theory_cls = [theory_kCMB_E, theory_kCMB_B]
        theory_cls = [theory_kCMB_E+noise_cls, theory_kCMB_B+noise_cls]

        theory_pcl = w.couple_cell(theory_cls)

        # binned_theory_pcls['kCMB_E'] = pbl @ (theory_pcl[0][output_lmin:output_lmax + 1]
        #                                      + noise_cls[output_lmin:output_lmax + 1])
        #
        # binned_theory_pcls['kCMB_B'] = pbl @ (theory_pcl[1][output_lmin:output_lmax + 1]
        #                                      + noise_cls[output_lmin:output_lmax + 1])

        binned_theory_pcls['kCMB_E'] = pbl @ (theory_pcl[0][output_lmin:output_lmax + 1])

        binned_theory_pcls['kCMB_B'] = pbl @ (theory_pcl[1][output_lmin:output_lmax + 1])

    bp_save_dir = setup_theory_cls(cl_dir=theory_cl_dir, spectra_type=spectra_type, bin_i=bin_i, bin_j=bin_j)[1]

    np.savetxt(bp_save_dir + 'PCl_Bandpowers_{}_bin_{}_{}.txt'.format(spectra_type, bin_i, bin_j),
               np.transpose(binned_theory_pcls[spectra_type]))

    # if bin_i == bin_j:
    #     if os.path.isfile(bp_save_dir + 'ell_bp_bin_{}.txt'.format(bin_i)) is False:
    #         np.savetxt(bp_save_dir + 'ell_bp_bin_{}.txt'.format(bin_i),
    #                    np.transpose(ell_arr))
    #
    # if os.path.isfile(bp_save_dir + 'ell_bp.txt') is False:
    #     np.savetxt(bp_save_dir + 'ell_bp.txt',
    #                np.transpose(ell_arr))

    if os.path.isfile(bp_save_dir + 'ell_bp_bin_{}_{}.txt'.format(bin_i,bin_j)) is False:
        np.savetxt(bp_save_dir + 'ell_bp_bin_{}_{}.txt'.format(bin_i,bin_j),
                   np.transpose(ell_arr))


def process_22_pcls(config_dict, theory_cl_dir, noise_cl_dir, spectra_type, bin_i, bin_j, obs_mask_path, output_lmin,
                    output_lmax, ell_arr, pbl):

    """
    Function to convert fiducial full-sky 22 components of the 3x2pt power spectra into predicted Pseudo-bandpowers.
    First couple the full-sky spectra with the mask to produce Pseudo-Cls. Then combine with the bandpower binning and
    include noise model.

    Parameters
    ----------
    config_dict (dict): Config dictionary of pipeline/conversion variables
    theory_cl_dir (str):    Path to location of fiducial full-sky power spectra
    noise_cl_dir (str):     Path to location of predicted noise power spectra
    spectra_type (str): Which spectra type (i.e. which component of the 3x2pt). For 22 must be 'EE', 'EB', 'BE', or
                        'BB' for shear.
    bin_i (float):  Tomographic bin id number of the first field
    bin_j (float):  Tomographic bin id number of the second field
    obs_mask_path (str):    Path to mask describing observed footprint
    ell_arr (arr):  Array of the 'effective' ells that correspond to the bandpowers
    pbl (arr):  Bandpower conversion matrix

    Returns
    -------
    Saves fiducial model of the 3x2pt 22 Pseudo bandpowers that include contribution from the expected noise.
    """

    input_lmin = config_dict['input_lmin']
    input_lmax = config_dict['input_lmax']

    nside = config_dict['nside']

    accepted_spectra_types = {'EE', 'EB', 'BE', 'BB'}
    if spectra_type not in accepted_spectra_types:
        print('Warning! Field Type Not Recognised - Exiting...')
        sys.exit()

    if obs_mask_path == 'None':
        obs_mask = np.ones(hp.nside2npix(nside))
    else:
        obs_mask = hp.read_map(obs_mask_path)

    # obs_mask = hp.read_map(obs_mask_path)

    f2 = nmt.NmtField(mask=obs_mask, maps=None, spin=2, lmax_sht=input_lmax)

    w = nmt.NmtWorkspace()
    w.compute_coupling_matrix(f2, f2, bins=nmt.NmtBin.from_lmax_linear(input_lmax, 1))

    theory_EE, theory_EB, theory_BE, theory_BB = [pad_cls(
        lmin=input_lmin,
        input_cls=setup_theory_cls(
            cl_dir=theory_cl_dir,
            spectra_type=spec_type,
            bin_i=bin_i,
            bin_j=bin_j)[0]) for spec_type in ['EE', 'EB', 'BE', 'BB']]

    noise_cls = pad_cls(
        lmin=0,
        input_cls=setup_theory_cls(
            cl_dir=noise_cl_dir,
            spectra_type=spectra_type,
            bin_i=bin_i,
            bin_j=bin_j)[0])

    # theory_cls = [theory_EE, theory_EB, theory_BE, theory_BB]
    theory_cls = [theory_EE+noise_cls, theory_EB, theory_BE, theory_BB+noise_cls]

    theory_pcls = w.couple_cell(theory_cls)

    # binned_theory_pcls = {
    #     'EE': pbl @ (theory_pcls[0][output_lmin:output_lmax + 1] + noise_cls[output_lmin:output_lmax + 1]),
    #     'EB': pbl @ (theory_pcls[1][output_lmin:output_lmax + 1] + noise_cls[output_lmin:output_lmax + 1]),
    #     'BE': pbl @ (theory_pcls[2][output_lmin:output_lmax + 1] + noise_cls[output_lmin:output_lmax + 1]),
    #     'BB': pbl @ (theory_pcls[3][output_lmin:output_lmax + 1] + noise_cls[output_lmin:output_lmax + 1])
    # }

    binned_theory_pcls = {
        'EE': pbl @ (theory_pcls[0][output_lmin:output_lmax + 1]),
        'EB': pbl @ (theory_pcls[1][output_lmin:output_lmax + 1]),
        'BE': pbl @ (theory_pcls[2][output_lmin:output_lmax + 1]),
        'BB': pbl @ (theory_pcls[3][output_lmin:output_lmax + 1])
    }

    bp_save_dir = setup_theory_cls(cl_dir=theory_cl_dir, spectra_type=spectra_type, bin_i=bin_i, bin_j=bin_j)[1]

    np.savetxt(bp_save_dir + 'PCl_Bandpowers_{}_bin_{}_{}.txt'.format(spectra_type, bin_i, bin_j),
               np.transpose(binned_theory_pcls[spectra_type]))

    # if bin_i == bin_j:
    #     if os.path.isfile(bp_save_dir + 'ell_bp_bin_{}.txt'.format(bin_i)) is False:
    #         np.savetxt(bp_save_dir + 'ell_bp_bin_{}.txt'.format(bin_i),
    #                    np.transpose(ell_arr))

    # if os.path.isfile(bp_save_dir + 'ell_bp.txt') is False:
    #     np.savetxt(bp_save_dir + 'ell_bp.txt',
    #                np.transpose(ell_arr))

    if os.path.isfile(bp_save_dir + 'ell_bp_bin_{}_{}.txt'.format(bin_i,bin_j)) is False:
        np.savetxt(bp_save_dir + 'ell_bp_bin_{}_{}.txt'.format(bin_i,bin_j),
                   np.transpose(ell_arr))


def execute(pipeline_variables_path):

    """
    Main function to execute bandpower measurement and modelling to generate predicted bandpowers.
    """

    # First create dictionary of calculation parameters and extract useful quantities

    # pipeline_variables_path = os.environ['PIPELINE_VARIABLES_PATH']
    config_dict = measure_bps_config(pipeline_variables_path=pipeline_variables_path)

    save_dir = config_dict['save_dir']
    nside = config_dict['nside']
    nbins = config_dict['nbins']
    no_iter = config_dict['no_iter']
    mask_path = config_dict['mask_path']
    cmb_mask_path = config_dict['cmb_mask_path']

    n_bandpowers = config_dict['n_bandpowers']
    input_lmin = config_dict['input_lmin']
    input_lmax = config_dict['input_lmax']

    output_lmin_shear = config_dict['output_lmin_shear']
    output_lmax_shear = config_dict['output_lmax_shear']
    pbl_shear = config_dict['pbl_shear']
    ell_arr_shear = config_dict['ell_arr_shear']

    output_lmin_galaxy_shear = config_dict['output_lmin_galaxy_shear']
    output_lmax_galaxy_shear = config_dict['output_lmax_galaxy_shear']
    pbl_galaxy_shear = config_dict['pbl_galaxy_shear']
    ell_arr_galaxy_shear = config_dict['ell_arr_galaxy_shear']

    output_lmin_galaxy = config_dict['output_lmin_galaxy']
    output_lmax_galaxy = config_dict['output_lmax_galaxy']
    pbl_galaxy = config_dict['pbl_galaxy']
    ell_arr_galaxy = config_dict['ell_arr_galaxy']

    output_lmin_cmbkk = config_dict['output_lmin_cmbkk']
    output_lmax_cmbkk = config_dict['output_lmax_cmbkk']
    pbl_cmbkk = config_dict['pbl_cmbkk']
    ell_arr_cmbkk = config_dict['ell_arr_cmbkk']

    output_lmin_cmbkk_galaxy = config_dict['output_lmin_cmbkk_galaxy']
    output_lmax_cmbkk_galaxy = config_dict['output_lmax_cmbkk_galaxy']
    pbl_cmbkk_galaxy = config_dict['pbl_cmbkk_galaxy']
    ell_arr_cmbkk_galaxy = config_dict['ell_arr_cmbkk_galaxy']

    output_lmin_cmbkk_shear = config_dict['output_lmin_cmbkk_shear']
    output_lmax_cmbkk_shear = config_dict['output_lmax_cmbkk_shear']
    pbl_cmbkk_shear = config_dict['pbl_cmbkk_shear']
    ell_arr_cmbkk_shear = config_dict['ell_arr_cmbkk_shear']

    # Define some paths to extract data on disk and save measured quantities.

    recov_cat_cls_dir = save_dir + 'raw_6x2pt_cls/'
    obs_cat_cls_dir = save_dir + 'measured_6x2pt_cls/'
    obs_noise_cls_dir = save_dir + 'measured_noise_cls/'

    obs_cat_bps_dir = save_dir + 'measured_6x2pt_bps/'

    gal_bps_dir = obs_cat_bps_dir + 'galaxy_bp/'
    shear_bps_dir = obs_cat_bps_dir + 'shear_bp/'
    gal_shear_bps_dir = obs_cat_bps_dir + 'galaxy_shear_bp/'

    k_bps_dir = shear_bps_dir + 'Cl_TT/'
    y1_bps_dir = shear_bps_dir + 'Cl_EE/'
    y1y2_bps_dir = shear_bps_dir + 'Cl_EB/'
    y2y1_bps_dir = shear_bps_dir + 'Cl_BE/'
    y2_bps_dir = shear_bps_dir + 'Cl_BB/'

    kCMB_bps_dir = obs_cat_bps_dir + 'cmbkappa_bp/'
    kCMB_gal_bps_dir = obs_cat_bps_dir + 'galaxy_cmbkappa_bp/'
    kCMB_E_bps_dir = obs_cat_bps_dir + 'shear_cmbkappa_bp/kCMB_E/'
    kCMB_B_bps_dir = obs_cat_bps_dir + 'shear_cmbkappa_bp/kCMB_B/'

    # for folder in [gal_bps_dir]:
    #     if not os.path.exists(folder):
    #         os.makedirs(folder)
    #     for i in range(nbins):
    #         np.savetxt(folder + 'ell_bin_{}.txt'.format(i+1),
    #                    np.transpose(ell_arr_galaxy[i]))
    #
    # for folder in [gal_shear_bps_dir]:
    #     if not os.path.exists(folder):
    #         os.makedirs(folder)
    #     for i in range(nbins):
    #         np.savetxt(folder + 'ell_bin_{}.txt'.format(i+1),
    #                    np.transpose(ell_arr_galaxy_shear[i]))
    #
    # for folder in [shear_bps_dir, k_bps_dir, y1_bps_dir, y1y2_bps_dir, y2y1_bps_dir, y2_bps_dir]:
    #     if not os.path.exists(folder):
    #         os.makedirs(folder)
    #     for i in range(nbins):
    #         np.savetxt(folder + 'ell_bin_{}.txt'.format(i+1),
    #                    np.transpose(ell_arr_shear[i]))
    #
    # for folder in [kCMB_bps_dir]:
    #     if not os.path.exists(folder):
    #         os.makedirs(folder)
    #     np.savetxt(folder + 'ell_bin_1.txt',
    #                np.transpose(ell_arr_cmbkk))
    #
    # for folder in [kCMB_gal_bps_dir]:
    #     if not os.path.exists(folder):
    #         os.makedirs(folder)
    #     for i in range(nbins):
    #         np.savetxt(folder + 'ell_bin_{}.txt'.format(i+1),
    #                    np.transpose(ell_arr_cmbkk_galaxy[i]))
    #
    # for folder in [kCMB_E_bps_dir, kCMB_B_bps_dir]:
    #     if not os.path.exists(folder):
    #         os.makedirs(folder)
    #
    #     for i in range(nbins):
    #         np.savetxt(folder + 'ell_bin_{}.txt'.format(i+1),
    #                    np.transpose(ell_arr_cmbkk_shear[i]))
    #

    gal_cl_dir = recov_cat_cls_dir + 'galaxy_cl/'
    shear_cl_dir = recov_cat_cls_dir + 'shear_cl/'
    gal_shear_cl_dir = recov_cat_cls_dir + 'galaxy_shear_cl/'
    cmbkk_cl_dir = recov_cat_cls_dir + 'cmbkappa_cl/'
    cmbkk_gal_cl_dir = recov_cat_cls_dir + 'galaxy_cmbkappa_cl/'
    cmbkk_E_cl_dir = recov_cat_cls_dir + 'shear_cmbkappa_cl/kCMB_E/'
    cmbkk_B_cl_dir = recov_cat_cls_dir + 'shear_cmbkappa_cl/kCMB_B/'

    obs_gal_cl_dir = obs_cat_cls_dir + 'galaxy_cl/'
    obs_shear_cl_dir = obs_cat_cls_dir + 'shear_cl/'
    obs_gal_shear_cl_dir = obs_cat_cls_dir + 'galaxy_shear_cl/'
    obs_cmbkk_cl_dir = obs_cat_cls_dir + 'cmbkappa_cl/'
    obs_cmbkk_gal_cl_dir = obs_cat_cls_dir + 'galaxy_cmbkappa_cl/'
    obs_cmbkk_E_cl_dir = obs_cat_cls_dir + 'shear_cmbkappa_cl/kCMB_E/'
    obs_cmbkk_B_cl_dir = obs_cat_cls_dir + 'shear_cmbkappa_cl/kCMB_B/'

    theory_cls_dir = save_dir + 'fiducial_cosmology/'
    noise_cls_dir = save_dir + 'raw_noise_cls/'

    for i in range(nbins):

        mix_mats_save_path = save_dir + 'mixmats_bin{}.npz'.format(i+1)

        mask.get_6x2pt_mixmats(mask_path=mask_path,
                               mask_path_cmb=cmb_mask_path,
                               nside=nside,
                               lmin=input_lmin,
                               input_lmax=input_lmax,
                               lmax_out_nn=output_lmax_galaxy[i],
                               lmax_out_ne=output_lmax_galaxy_shear[i],
                               lmax_out_ee=output_lmax_shear[i],
                               lmax_out_ek=output_lmax_cmbkk_shear[i],
                               lmax_out_nk=output_lmax_cmbkk_galaxy[i],
                               lmax_out_kk=output_lmax_cmbkk,
                               save_path=mix_mats_save_path)

    # Create null spectra
    create_null_spectras(nbins=nbins, lmin=input_lmin, lmax=input_lmax, output_dir=theory_cls_dir)
    create_null_spectras(nbins=nbins, lmin=0, lmax=input_lmax, output_dir=noise_cls_dir)

    # shutil.copytree(save_dir + 'fiducial_cosmology/shear_cl', theory_cls_dir + 'shear_cl')
    # shutil.copytree(save_dir + 'fiducial_cosmology/galaxy_cl', theory_cls_dir + 'galaxy_cl')
    # shutil.copytree(save_dir + 'fiducial_cosmology/galaxy_shear_cl', theory_cls_dir + 'galaxy_shear_cl')

    # Convert Cls to bandpowers for each realisation
    for it in range(no_iter):

        gal_cl_it_dir = gal_cl_dir + 'iter_{}/'.format(it + 1)
        gal_bp_it_dir = gal_bps_dir + 'iter_{}/'.format(it + 1)

        gal_shear_cl_it_dir = gal_shear_cl_dir + 'iter_{}/'.format(it + 1)
        gal_shear_bp_it_dir = gal_shear_bps_dir + 'iter_{}/'.format(it + 1)

        cmbkk_cl_it_dir = cmbkk_cl_dir + 'iter_{}/'.format(it+1)
        cmbkk_bp_it_dir = kCMB_bps_dir + 'iter_{}/'.format(it+1)

        cmbkk_gal_cl_it_dir = cmbkk_gal_cl_dir + 'iter_{}/'.format(it+1)
        cmbkk_gal_bp_it_dir = kCMB_gal_bps_dir + 'iter_{}/'.format(it+1)

        cmbkk_E_cl_it_dir = cmbkk_E_cl_dir + 'iter_{}/'.format(it+1)
        cmbkk_E_bp_it_dir = kCMB_E_bps_dir + 'iter_{}/'.format(it+1)

        cmbkk_B_cl_it_dir = cmbkk_B_cl_dir + 'iter_{}/'.format(it+1)
        cmbkk_B_bp_it_dir = kCMB_B_bps_dir + 'iter_{}/'.format(it+1)

        # Convert raw PCls to measured PCls for each realisation of cmbkappa_cl
        measured_cls_to_obs_cls(
            measured_cls_dir=cmbkk_cl_it_dir,
            obs_cls_dir=obs_cmbkk_cl_dir + 'iter_{}/'.format(it + 1),
            bin_i=1,
            bin_j=1,
            lmin_out=output_lmin_cmbkk,
            lmax_out=output_lmax_cmbkk)
        # Convert 'observed' PCls to bandpowers for eaxh realisation of cmbkappa
        cl_to_bp(cl_dir=obs_cmbkk_cl_dir + 'iter_{}/'.format(it + 1),
                 bp_dir=cmbkk_bp_it_dir,
                 bin_i=1,
                 bin_j=1,
                 pbl=pbl_cmbkk)

        for i in range(nbins):

            # Convert raw PCls to measured PCls for each realisation of galaxy_cmbkappa
            measured_cls_to_obs_cls(
                measured_cls_dir=cmbkk_gal_cl_it_dir,
                obs_cls_dir=obs_cmbkk_gal_cl_dir + 'iter_{}/'.format(it + 1),
                bin_i=i+1,
                bin_j=1,
                lmin_out=output_lmin_cmbkk_galaxy,
                lmax_out=output_lmax_cmbkk_galaxy[i])
            # Convert 'observed' PCls to bandpowers for each realisation of galaxy_cmbkappa
            cl_to_bp(cl_dir=obs_cmbkk_gal_cl_dir + 'iter_{}/'.format(it + 1),
                     bp_dir=cmbkk_gal_bp_it_dir,
                     bin_i=i+1,
                     bin_j=1,
                     pbl=pbl_cmbkk_galaxy[i])

            # Convert raw PCls to measured PCls for each realisation of cmbkappa_shear-E
            measured_cls_to_obs_cls(
                measured_cls_dir=cmbkk_E_cl_it_dir,
                obs_cls_dir=obs_cmbkk_E_cl_dir + 'iter_{}/'.format(it + 1),
                bin_i=i+1,
                bin_j=1,
                lmin_out=output_lmin_cmbkk_shear,
                lmax_out=output_lmax_cmbkk_shear[i])
            # Convert 'observed' PCls to bandpowers for each realisation of cmbkappa_shear-E
            cl_to_bp(cl_dir=obs_cmbkk_E_cl_dir + 'iter_{}/'.format(it + 1),
                     bp_dir=cmbkk_E_bp_it_dir,
                     bin_i=i+1,
                     bin_j=1,
                     pbl=pbl_cmbkk_shear[i])

            # Convert raw PCls to measured PCls for each realisation of cmbkappa_shear-B
            measured_cls_to_obs_cls(
                measured_cls_dir=cmbkk_B_cl_it_dir,
                obs_cls_dir=obs_cmbkk_B_cl_dir + 'iter_{}/'.format(it + 1),
                bin_i=i+1,
                bin_j=1,
                lmin_out=output_lmin_cmbkk_shear,
                lmax_out=output_lmax_cmbkk_shear[i])
            # Convert 'observed' PCls to bandpowers for each realisation of cmbkappa_shear-B
            cl_to_bp(cl_dir=obs_cmbkk_B_cl_dir + 'iter_{}/'.format(it + 1),
                     bp_dir=cmbkk_B_bp_it_dir,
                     bin_i=i+1,
                     bin_j=1,
                     pbl=pbl_cmbkk_shear[i])

            for j in range(nbins):

                # Convert raw PCls to measured PCls for each realisation of galaxy_shear
                measured_cls_to_obs_cls(
                    measured_cls_dir=gal_shear_cl_it_dir,
                    obs_cls_dir=obs_gal_shear_cl_dir + 'iter_{}/'.format(it + 1),
                    bin_i=i + 1,
                    bin_j=j + 1,
                    lmin_out=output_lmin_galaxy_shear,
                    lmax_out=min(output_lmax_galaxy_shear[i], output_lmax_galaxy_shear[j]))
                # Convert 'observed' PCls to bandpowers for each realisation of galaxy_shear
                if output_lmax_galaxy_shear[i] < output_lmax_galaxy_shear[j]:
                    this_pbl_galaxy_shear = pbl_galaxy_shear[i]
                else:
                    this_pbl_galaxy_shear = pbl_galaxy_shear[j]

                cl_to_bp(cl_dir=obs_gal_shear_cl_dir + 'iter_{}/'.format(it + 1),
                         bp_dir=gal_shear_bp_it_dir,
                         bin_i=i + 1,
                         bin_j=j + 1,
                         pbl=this_pbl_galaxy_shear)

                if i >= j:

                    # Convert raw PCls to measured PCls for each realisation of galaxy_galaxy
                    measured_cls_to_obs_cls(
                        measured_cls_dir=gal_cl_it_dir,
                        obs_cls_dir=obs_gal_cl_dir + 'iter_{}/'.format(it + 1),
                        bin_i=i + 1,
                        bin_j=j + 1,
                        lmin_out=output_lmin_galaxy,
                        lmax_out=min(output_lmax_galaxy[i], output_lmax_galaxy[j]))
                    # Convert 'observed' PCls to bandpowers for each realisation of galaxy_galaxy

                    if output_lmax_galaxy[i] < output_lmax_galaxy[j]:
                        this_pbl_galaxy = pbl_galaxy[i]
                    else:
                        this_pbl_galaxy = pbl_galaxy[j]

                    cl_to_bp(cl_dir=obs_gal_cl_dir + 'iter_{}/'.format(it + 1),
                             bp_dir=gal_bp_it_dir,
                             bin_i=i + 1,
                             bin_j=j + 1,
                             pbl=this_pbl_galaxy)

                    for shear_component_dir in ['Cl_TT/', 'Cl_EE/', 'Cl_EB/', 'Cl_BE/', 'Cl_BB/']:
                        shear_cl_it_dir = shear_cl_dir + shear_component_dir + 'iter_{}/'.format(it + 1)
                        shear_bp_it_dir = shear_bps_dir + shear_component_dir + 'iter_{}/'.format(it + 1)

                        # Convert raw PCls to measured PCls for each realisation of shear_shear (per component)
                        measured_cls_to_obs_cls(
                            measured_cls_dir=shear_cl_it_dir,
                            obs_cls_dir=obs_shear_cl_dir + shear_component_dir + 'iter_{}/'.format(it + 1),
                            bin_i=i + 1,
                            bin_j=j + 1,
                            lmin_out=output_lmin_shear,
                            lmax_out=min(output_lmax_shear[i], output_lmax_shear[j]))
                        # Convert 'observed' PCls to bandpowers for each realisation of shear_shear (per component)

                        if output_lmax_shear[i] < output_lmax_shear[j]:
                            this_pbl_shear = pbl_shear[i]
                        else:
                            this_pbl_shear = pbl_shear[j]

                        cl_to_bp(cl_dir=obs_shear_cl_dir + shear_component_dir + 'iter_{}/'.format(it + 1),
                                 bp_dir=shear_bp_it_dir,
                                 bin_i=i + 1,
                                 bin_j=j + 1,
                                 pbl=this_pbl_shear)

    # Now convert Cls to bandpowers for the average Cl quantities, and generate theoretical prediction for bandpowers

    ####################################################################################################################
    # JW 04/04/2025 - edited up to here for the full 6x2pt analysis. Converted all realisations of 6x2pt into
    # measured/observed PCls, and Pseudo-bandpowers. Then converted the **averaged** quantities into
    # measured/observed PCls and Pseudo-bandpowers.
    #
    # NOW NEED TO CONVERT THE FIDUCIAL CLS INTO PREDICTED PSEUDO BANDPOWERS FOR ALL COMPONENTS OF 6X2PT. BASE CODE DOES
    # THIS ALREADY FO 3X2PT, NOW NEED TO EXTEND TO CMB CORRELATIONS! TO DO NEXT WEEK!!
    ####################################################################################################################

    # cmbkappa
    measured_cls_to_obs_cls(
        measured_cls_dir=cmbkk_cl_dir,
        obs_cls_dir=obs_cmbkk_cl_dir,
        bin_i=1,
        bin_j=1,
        lmin_out=output_lmin_cmbkk,
        lmax_out=output_lmax_cmbkk)

    measured_cls_to_obs_cls(
        measured_cls_dir=noise_cls_dir + 'cmbkappa_cl/',
        obs_cls_dir=obs_noise_cls_dir + 'cmbkappa_cl/',
        bin_i=1,
        bin_j=1,
        lmin_out=output_lmin_cmbkk,
        lmax_out=output_lmax_cmbkk)

    cl_to_bp(cl_dir=obs_cmbkk_cl_dir, bp_dir=kCMB_bps_dir, bin_i=1, bin_j=1, pbl=pbl_cmbkk, ell_arr=ell_arr_cmbkk)
    calc_stdem_bps(bp_dir=kCMB_bps_dir, n_bps=n_bandpowers, bin_i=1, bin_j=1, realisations=no_iter)

    process_00_pcls(
        config_dict=config_dict,
        theory_cl_dir=theory_cls_dir,
        noise_cl_dir=noise_cls_dir,
        spectra_type='kCMB_kCMB',
        bin_i=1,
        bin_j=1,
        obs_mask_path=cmb_mask_path,
        output_lmin=output_lmin_cmbkk,
        output_lmax=output_lmax_cmbkk,
        ell_arr=ell_arr_cmbkk,
        pbl=pbl_cmbkk)

    for i in range(nbins):

        # galaxy_cmbkappa
        measured_cls_to_obs_cls(
            measured_cls_dir=cmbkk_gal_cl_dir,
            obs_cls_dir=obs_cmbkk_gal_cl_dir,
            bin_i=i+1,
            bin_j=1,
            lmin_out=output_lmin_cmbkk_galaxy,
            lmax_out=output_lmax_cmbkk_galaxy[i])

        measured_cls_to_obs_cls(
            measured_cls_dir=noise_cls_dir + 'galaxy_cmbkappa_cl/',
            obs_cls_dir=obs_noise_cls_dir + 'galaxy_cmbkappa_cl/',
            bin_i=i+1,
            bin_j=1,
            lmin_out=output_lmin_cmbkk_galaxy,
            lmax_out=output_lmax_cmbkk_galaxy[i])

        cl_to_bp(cl_dir=obs_cmbkk_gal_cl_dir, bp_dir=kCMB_gal_bps_dir, bin_i=i+1, bin_j=1, pbl=pbl_cmbkk_galaxy[i],ell_arr=ell_arr_cmbkk_galaxy[i])
        calc_stdem_bps(bp_dir=kCMB_gal_bps_dir, n_bps=n_bandpowers, bin_i=i+1, bin_j=1, realisations=no_iter)

        process_00_pcls(
            config_dict=config_dict,
            theory_cl_dir=theory_cls_dir,
            noise_cl_dir=noise_cls_dir,
            spectra_type='kCMB_gal',
            bin_i=i+1,
            bin_j=1,
            obs_mask_path=[mask_path, cmb_mask_path],
            output_lmin=output_lmin_cmbkk_galaxy,
            output_lmax=output_lmax_cmbkk_galaxy[i],
            ell_arr=ell_arr_cmbkk_galaxy[i],
            pbl=pbl_cmbkk_galaxy[i])

        # shear_cmbkappa (E mode component)
        measured_cls_to_obs_cls(
            measured_cls_dir=cmbkk_E_cl_dir,
            obs_cls_dir=obs_cmbkk_E_cl_dir,
            bin_i=i+1,
            bin_j=1,
            lmin_out=output_lmin_cmbkk_shear,
            lmax_out=output_lmax_cmbkk_shear[i])

        measured_cls_to_obs_cls(
            measured_cls_dir=noise_cls_dir + 'shear_cmbkappa_cl/',
            obs_cls_dir=obs_noise_cls_dir + 'shear_cmbkappa_cl/',
            bin_i=i+1,
            bin_j=1,
            lmin_out=output_lmin_cmbkk_shear,
            lmax_out=output_lmax_cmbkk_shear[i])

        cl_to_bp(cl_dir=obs_cmbkk_E_cl_dir, bp_dir=kCMB_E_bps_dir, bin_i=i+1, bin_j=1, pbl=pbl_cmbkk_shear[i],ell_arr=ell_arr_cmbkk_shear[i])
        calc_stdem_bps(bp_dir=kCMB_E_bps_dir, n_bps=n_bandpowers, bin_i=i+1, bin_j=1, realisations=no_iter)

        process_02_pcls(
            config_dict=config_dict,
            theory_cl_dir=theory_cls_dir,
            noise_cl_dir=noise_cls_dir,
            spectra_type='kCMB_E',
            bin_i=i + 1,
            bin_j=1,
            obs_mask_path=[mask_path, cmb_mask_path],
            output_lmin=output_lmin_cmbkk_shear,
            output_lmax=output_lmax_cmbkk_shear[i],
            ell_arr=ell_arr_cmbkk_shear[i],
            pbl=pbl_cmbkk_shear[i])

        # shear_cmbkappa (B mode component)
        measured_cls_to_obs_cls(
            measured_cls_dir=cmbkk_B_cl_dir,
            obs_cls_dir=obs_cmbkk_B_cl_dir,
            bin_i=i+1,
            bin_j=1,
            lmin_out=output_lmin_cmbkk_shear,
            lmax_out=output_lmax_cmbkk_shear[i])

        cl_to_bp(cl_dir=obs_cmbkk_B_cl_dir, bp_dir=kCMB_B_bps_dir, bin_i=i+1, bin_j=1, pbl=pbl_cmbkk_shear[i],ell_arr=ell_arr_cmbkk_shear[i])
        calc_stdem_bps(bp_dir=kCMB_B_bps_dir, n_bps=n_bandpowers, bin_i=i+1, bin_j=1, realisations=no_iter)

        process_02_pcls(
            config_dict=config_dict,
            theory_cl_dir=theory_cls_dir,
            noise_cl_dir=noise_cls_dir,
            spectra_type='kCMB_B',
            bin_i=i + 1,
            bin_j=1,
            obs_mask_path=[mask_path, cmb_mask_path],
            output_lmin=output_lmin_cmbkk_shear,
            output_lmax=output_lmax_cmbkk_shear[i],
            ell_arr=ell_arr_cmbkk_shear[i],
            pbl=pbl_cmbkk_shear[i])

        for j in range(nbins):

            # Cut the raw PCls measured from Catalogues to a specific range in lmin, lmax
            measured_cls_to_obs_cls(
                measured_cls_dir=gal_shear_cl_dir,
                obs_cls_dir=obs_gal_shear_cl_dir,
                bin_i=i + 1,
                bin_j=j + 1,
                lmin_out=output_lmin_galaxy_shear,
                lmax_out=min(output_lmax_galaxy_shear[i],output_lmax_galaxy_shear[j]))

            measured_cls_to_obs_cls(
                measured_cls_dir=noise_cls_dir + 'galaxy_shear_cl/',
                obs_cls_dir=obs_noise_cls_dir + 'galaxy_shear_cl/',
                bin_i=i + 1,
                bin_j=j + 1,
                lmin_out=output_lmin_galaxy_shear,
                lmax_out=min(output_lmax_galaxy_shear[i],output_lmax_galaxy_shear[j]))

            if output_lmax_galaxy_shear[i] < output_lmax_galaxy_shear[j]:
                this_pbl_galaxy_shear = pbl_galaxy_shear[i]
                this_ell_arr_galaxy_shear = ell_arr_galaxy_shear[i]
            else:
                this_pbl_galaxy_shear = pbl_galaxy_shear[j]
                this_ell_arr_galaxy_shear = ell_arr_galaxy_shear[j]

            # Convert Pseudo-Cl for measured GGL into bandpower
            cl_to_bp(cl_dir=obs_gal_shear_cl_dir, bp_dir=gal_shear_bps_dir, bin_i=i + 1, bin_j=j + 1, pbl=this_pbl_galaxy_shear, ell_arr=this_ell_arr_galaxy_shear)
            calc_stdem_bps(bp_dir=gal_shear_bps_dir, n_bps=n_bandpowers, bin_i=i + 1, bin_j=j + 1, realisations=no_iter)

            # Calculate the theoretical PCl bandpower for the fiducial full-sky GGL
            process_02_pcls(
                config_dict=config_dict,
                theory_cl_dir=theory_cls_dir,
                noise_cl_dir=noise_cls_dir,
                spectra_type='gal_E',
                bin_i=i + 1,
                bin_j=j + 1,
                obs_mask_path=mask_path,
                output_lmin=output_lmin_galaxy_shear,
                output_lmax=min(output_lmax_galaxy_shear[i],output_lmax_galaxy_shear[j]),
                ell_arr=this_ell_arr_galaxy_shear,
                pbl=this_pbl_galaxy_shear)

            if i >= j:

                measured_cls_to_obs_cls(
                    measured_cls_dir=gal_cl_dir,
                    obs_cls_dir=obs_gal_cl_dir,
                    bin_i=i + 1,
                    bin_j=j + 1,
                    lmin_out=output_lmin_galaxy,
                    lmax_out=min(output_lmax_galaxy[i],output_lmax_galaxy[j]))

                measured_cls_to_obs_cls(
                    measured_cls_dir=noise_cls_dir + 'galaxy_cl/',
                    obs_cls_dir=obs_noise_cls_dir + 'galaxy_cl/',
                    bin_i=i + 1,
                    bin_j=j + 1,
                    lmin_out=output_lmin_galaxy,
                    lmax_out=min(output_lmax_galaxy[i],output_lmax_galaxy[j]))

                if output_lmax_galaxy[i] < output_lmax_galaxy[j]:
                    this_pbl_galaxy = pbl_galaxy[i]
                    this_ell_arr_galaxy = ell_arr_galaxy[i]
                else:
                    this_pbl_galaxy = pbl_galaxy[j]
                    this_ell_arr_galaxy = ell_arr_galaxy[j]

                cl_to_bp(cl_dir=obs_gal_cl_dir, bp_dir=gal_bps_dir, bin_i=i + 1, bin_j=j + 1, pbl=this_pbl_galaxy,ell_arr=this_ell_arr_galaxy)
                calc_stdem_bps(bp_dir=gal_bps_dir, n_bps=n_bandpowers, bin_i=i + 1, bin_j=j + 1,
                               realisations=no_iter)

                process_00_pcls(
                    config_dict=config_dict,
                    theory_cl_dir=theory_cls_dir,
                    noise_cl_dir=noise_cls_dir,
                    spectra_type='gal_gal',
                    bin_i=i + 1,
                    bin_j=j + 1,
                    obs_mask_path=mask_path,
                    output_lmin=output_lmin_galaxy,
                    output_lmax=min(output_lmax_galaxy[i],output_lmax_galaxy[j]),
                    ell_arr=this_ell_arr_galaxy,
                    pbl=this_pbl_galaxy)

                measured_cls_to_obs_cls(
                    measured_cls_dir=noise_cls_dir + 'shear_cl/',
                    obs_cls_dir=obs_noise_cls_dir + 'shear_cl/',
                    bin_i=i + 1,
                    bin_j=j + 1,
                    lmin_out=output_lmin_shear,
                    lmax_out=min(output_lmax_shear[i],output_lmax_shear[j]))

                for shear_component_dir in ['Cl_TT/', 'Cl_EE/', 'Cl_EB/', 'Cl_BE/', 'Cl_BB/']:
                    measured_cls_to_obs_cls(
                        measured_cls_dir=shear_cl_dir + shear_component_dir,
                        obs_cls_dir=obs_shear_cl_dir + shear_component_dir,
                        bin_i=i + 1,
                        bin_j=j + 1,
                        lmin_out=output_lmin_shear,
                        lmax_out=min(output_lmax_shear[i],output_lmax_shear[j]))

                    if output_lmax_shear[i] < output_lmax_shear[j]:
                        this_pbl_shear = pbl_shear[i]
                        this_ell_arr_shear = ell_arr_shear[i]
                    else:
                        this_pbl_shear = pbl_shear[j]
                        this_ell_arr_shear = ell_arr_shear[j]

                    cl_to_bp(
                        cl_dir=obs_shear_cl_dir + shear_component_dir,
                        bp_dir=shear_bps_dir + shear_component_dir,
                        bin_i=i + 1,
                        bin_j=j + 1,
                        pbl=this_pbl_shear,
                        ell_arr=this_ell_arr_shear
                    )

                    calc_stdem_bps(bp_dir=shear_bps_dir + shear_component_dir, n_bps=n_bandpowers, bin_i=i + 1,
                                   bin_j=j + 1, realisations=no_iter)

                for spin2_component in ['EE', 'BB']:
                    process_22_pcls(
                        config_dict=config_dict,
                        theory_cl_dir=theory_cls_dir,
                        noise_cl_dir=noise_cls_dir,
                        spectra_type=spin2_component,
                        bin_i=i + 1,
                        bin_j=j + 1,
                        obs_mask_path=mask_path,
                        output_lmin=output_lmin_shear,
                        output_lmax=min(output_lmax_shear[i],output_lmax_shear[j]),
                        ell_arr=this_ell_arr_shear,
                        pbl=this_pbl_shear)


# if __name__ == '__main__':
#     main()
